/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.Globales;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;

import control.Carro;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author yerso
 */
public class Escenario extends javax.swing.JFrame implements Globales, KeyListener {

    /**
     * Creates new form Escenario
     */
    public Escenario() {
	
	initComponents();
	this.addKeyListener(this);
	this.setLocationRelativeTo(this);
	this.arrancarCarro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();
        lblScore = new javax.swing.JLabel();
        lblSpeedValue = new javax.swing.JLabel();
        lblSpeed = new javax.swing.JLabel();
        lblScoreValue = new javax.swing.JLabel();
        pnlEscenario = new EscenarioPanel(FONDOS_IMG[0]);
        lblCarro = new Carro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1150, 576));

        lblScore.setText("Score");

        lblSpeed.setText("Speed");

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblScoreValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSpeedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(895, Short.MAX_VALUE))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScoreValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpeedValue, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pnlEscenario.setMaximumSize(new java.awt.Dimension(1150, 500));
        pnlEscenario.setPreferredSize(new java.awt.Dimension(1150, 500));

        lblCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Car.png"))); // NOI18N

        javax.swing.GroupLayout pnlEscenarioLayout = new javax.swing.GroupLayout(pnlEscenario);
        pnlEscenario.setLayout(pnlEscenarioLayout);
        pnlEscenarioLayout.setHorizontalGroup(
            pnlEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscenarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlEscenarioLayout.setVerticalGroup(
            pnlEscenarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEscenarioLayout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(lblCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlEscenario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlEscenario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Escenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(() -> {
	    new Escenario().setVisible(true);
	});
    }

    public void updateValues() {
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {

	int c = e.getKeyCode();
	if (c == KeyEvent.VK_RIGHT) {
	    lblCarro.setBounds(lblCarro.getX() + DESPLAZO_CARRO, lblCarro.getY(), 75, 30);
	}
	if (c == KeyEvent.VK_LEFT) {
	    lblCarro.setBounds(lblCarro.getX() - DESPLAZO_CARRO, lblCarro.getY(), 75, 30);
	}
	if (c == KeyEvent.VK_UP) {
	    lblCarro.setBounds(lblCarro.getX(), lblCarro.getY() - DESPLAZO_CARRO, 75, 30);
	}
	if (c == KeyEvent.VK_DOWN) {
	    lblCarro.setBounds(lblCarro.getX(), lblCarro.getY() + DESPLAZO_CARRO, 75, 30);
	}
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }

    class EscenarioPanel extends javax.swing.JPanel {

	private BufferedImage image;
	private int w, h;

	public EscenarioPanel(String fname) {
	    //reads the image
	    try {
		image = ImageIO.read(new File(fname));
		w = image.getWidth();
		h = image.getHeight();
	    } catch (IOException ioe) {
		System.out.println("Could not read in the pic");
	    }
	}

	@Override
	public Dimension getPreferredSize() {
	    return new Dimension(w, h);
	}
	//this will draw the image

	@Override
	public void paintComponent(Graphics g) {
	    super.paintComponent(g);
	    g.drawImage(image, 0, 0, this);
	}
    }

    public void arrancarCarro() {
	if (!hilo.isAlive()) {
	    hilo.start();
	}
    }

    private Thread hilo = new Thread() {
	@Override
	public void run() {
	    while (true) {
		try {
		    Thread.sleep(100);
		} catch (java.lang.InterruptedException ie) {
		    System.out.println(ie.getMessage());
		}
		score++;
		lblScoreValue.setText(Integer.toString(score));
	    }
	}
    };
    
    int score = 0;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCarro;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblScoreValue;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JLabel lblSpeedValue;
    private javax.swing.JPanel pnlEscenario;
    private javax.swing.JPanel pnlInfo;
    // End of variables declaration//GEN-END:variables
}
